---
app: apache-php-plus
auto_deploy: true
context: development
domain: releaseapp.gethandsup.com
repo_name: watsonjon/apache-php-plus
hostnames:
- web: web-apache-php-plus-${env_id}.${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: web
  image: watsonjon/apache-php-plus/web
  build:
    context: app
  has_repo: true
  static: false
  ports:
  - type: node_port
    target_port: '80'
    port: '80'
  stateful: true
  volumes:
  - type: persistent
    name: somedata
    mount_path: "/var/lib/mysql"
workflows:
- name: setup
  order_from:
  - services.all
- name: teardown
  parallelize:
  - step: remove_environment
    tasks:
    - release.remove_environment
- name: patch
  order_from:
  - services.web
